name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="Horror Story Generator" \
                   --onefile \
                   --windowed \
                   --icon=static/icon.ico \
                   --add-data="static:static" \
                   --add-data="templates:templates" \
                   --add-data="utils:utils" \
                   app.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Horror-Story-Generator-macOS
        path: dist/
